package com.ga.wyc.domain.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcResponse.proto

public final class RpcResponse {
  private RpcResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *返回类型
     * </pre>
     *
     * <code>.MResponse.Code code = 1;</code>
     */
    int getCodeValue();
    /**
     * <pre>
     *返回类型
     * </pre>
     *
     * <code>.MResponse.Code code = 1;</code>
     */
    MResponse.Code getCode();

    /**
     * <pre>
     *返回路由
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    String getUrl();
    /**
     * <pre>
     *返回路由
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     *消息提示
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    String getMessage();
    /**
     * <pre>
     *消息提示
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *返回的数据类型
     * </pre>
     *
     * <code>.MResponse.ResultType resultType = 4;</code>
     */
    int getResultTypeValue();
    /**
     * <pre>
     *返回的数据类型
     * </pre>
     *
     * <code>.MResponse.ResultType resultType = 4;</code>
     */
    MResponse.ResultType getResultType();

    /**
     * <pre>
     *json返回格式
     * </pre>
     *
     * <code>string jsonResult = 5;</code>
     */
    String getJsonResult();
    /**
     * <pre>
     *json返回格式
     * </pre>
     *
     * <code>string jsonResult = 5;</code>
     */
    com.google.protobuf.ByteString
        getJsonResultBytes();

    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */
    int getResultCount();
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */
    boolean containsResult(
            String key);
    /**
     * Use {@link #getResultMap()} instead.
     */
    @Deprecated
    java.util.Map<String, com.google.protobuf.Any>
    getResult();
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */
    java.util.Map<String, com.google.protobuf.Any>
    getResultMap();
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */

    com.google.protobuf.Any getResultOrDefault(
            String key,
            com.google.protobuf.Any defaultValue);
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */

    com.google.protobuf.Any getResultOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code MResponse}
   */
  public  static final class MResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MResponse)
      MResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MResponse.newBuilder() to construct.
    private MResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MResponse() {
      code_ = 0;
      url_ = "";
      message_ = "";
      resultType_ = 0;
      jsonResult_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              resultType_ = rawValue;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              jsonResult_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                result_ = com.google.protobuf.MapField.newMapField(
                    ResultDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<String, com.google.protobuf.Any>
              result__ = input.readMessage(
                  ResultDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              result_.getMutableMap().put(
                  result__.getKey(), result__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcResponse.internal_static_MResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetResult();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcResponse.internal_static_MResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MResponse.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MResponse.Code}
     */
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *成功
       * </pre>
       *
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <pre>
       *业务失败
       * </pre>
       *
       * <code>EX_BUSS = 1;</code>
       */
      EX_BUSS(1),
      /**
       * <pre>
       *服务器错误
       * </pre>
       *
       * <code>EX_SERVER = 2;</code>
       */
      EX_SERVER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *成功
       * </pre>
       *
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <pre>
       *业务失败
       * </pre>
       *
       * <code>EX_BUSS = 1;</code>
       */
      public static final int EX_BUSS_VALUE = 1;
      /**
       * <pre>
       *服务器错误
       * </pre>
       *
       * <code>EX_SERVER = 2;</code>
       */
      public static final int EX_SERVER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Code valueOf(int value) {
        return forNumber(value);
      }

      public static Code forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return EX_BUSS;
          case 2: return EX_SERVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Code> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Code[] VALUES = values();

      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Code(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MResponse.Code)
    }

    /**
     * Protobuf enum {@code MResponse.ResultType}
     */
    public enum ResultType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *JSON
       * </pre>
       *
       * <code>JSON = 0;</code>
       */
      JSON(0),
      /**
       * <pre>
       *BINARY
       * </pre>
       *
       * <code>BINARY = 1;</code>
       */
      BINARY(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *JSON
       * </pre>
       *
       * <code>JSON = 0;</code>
       */
      public static final int JSON_VALUE = 0;
      /**
       * <pre>
       *BINARY
       * </pre>
       *
       * <code>BINARY = 1;</code>
       */
      public static final int BINARY_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ResultType valueOf(int value) {
        return forNumber(value);
      }

      public static ResultType forNumber(int value) {
        switch (value) {
          case 0: return JSON;
          case 1: return BINARY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResultType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultType>() {
              public ResultType findValueByNumber(int number) {
                return ResultType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MResponse.getDescriptor().getEnumTypes().get(1);
      }

      private static final ResultType[] VALUES = values();

      public static ResultType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResultType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MResponse.ResultType)
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *返回类型
     * </pre>
     *
     * <code>.MResponse.Code code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <pre>
     *返回类型
     * </pre>
     *
     * <code>.MResponse.Code code = 1;</code>
     */
    public Code getCode() {
      @SuppressWarnings("deprecation")
      Code result = Code.valueOf(code_);
      return result == null ? Code.UNRECOGNIZED : result;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile Object url_;
    /**
     * <pre>
     *返回路由
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *返回路由
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile Object message_;
    /**
     * <pre>
     *消息提示
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息提示
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTTYPE_FIELD_NUMBER = 4;
    private int resultType_;
    /**
     * <pre>
     *返回的数据类型
     * </pre>
     *
     * <code>.MResponse.ResultType resultType = 4;</code>
     */
    public int getResultTypeValue() {
      return resultType_;
    }
    /**
     * <pre>
     *返回的数据类型
     * </pre>
     *
     * <code>.MResponse.ResultType resultType = 4;</code>
     */
    public ResultType getResultType() {
      @SuppressWarnings("deprecation")
      ResultType result = ResultType.valueOf(resultType_);
      return result == null ? ResultType.UNRECOGNIZED : result;
    }

    public static final int JSONRESULT_FIELD_NUMBER = 5;
    private volatile Object jsonResult_;
    /**
     * <pre>
     *json返回格式
     * </pre>
     *
     * <code>string jsonResult = 5;</code>
     */
    public String getJsonResult() {
      Object ref = jsonResult_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jsonResult_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *json返回格式
     * </pre>
     *
     * <code>string jsonResult = 5;</code>
     */
    public com.google.protobuf.ByteString
        getJsonResultBytes() {
      Object ref = jsonResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jsonResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 6;
    private static final class ResultDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, com.google.protobuf.Any>newDefaultInstance(
                  RpcResponse.internal_static_MResponse_ResultEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, com.google.protobuf.Any> result_;
    private com.google.protobuf.MapField<String, com.google.protobuf.Any>
    internalGetResult() {
      if (result_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultDefaultEntryHolder.defaultEntry);
      }
      return result_;
    }

    public int getResultCount() {
      return internalGetResult().getMap().size();
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */

    public boolean containsResult(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetResult().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, com.google.protobuf.Any> getResult() {
      return getResultMap();
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */

    public java.util.Map<String, com.google.protobuf.Any> getResultMap() {
      return internalGetResult().getMap();
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */

    public com.google.protobuf.Any getResultOrDefault(
        String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, com.google.protobuf.Any> map =
          internalGetResult().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
     */

    public com.google.protobuf.Any getResultOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, com.google.protobuf.Any> map =
          internalGetResult().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != Code.SUCCESS.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (resultType_ != ResultType.JSON.getNumber()) {
        output.writeEnum(4, resultType_);
      }
      if (!getJsonResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, jsonResult_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetResult(),
          ResultDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != Code.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (resultType_ != ResultType.JSON.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, resultType_);
      }
      if (!getJsonResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, jsonResult_);
      }
      for (java.util.Map.Entry<String, com.google.protobuf.Any> entry
           : internalGetResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, com.google.protobuf.Any>
        result__ = ResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, result__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MResponse)) {
        return super.equals(obj);
      }
      MResponse other = (MResponse) obj;

      boolean result = true;
      result = result && code_ == other.code_;
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && resultType_ == other.resultType_;
      result = result && getJsonResult()
          .equals(other.getJsonResult());
      result = result && internalGetResult().equals(
          other.internalGetResult());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + RESULTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + resultType_;
      hash = (37 * hash) + JSONRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getJsonResult().hashCode();
      if (!internalGetResult().getMap().isEmpty()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MResponse)
        MResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcResponse.internal_static_MResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcResponse.internal_static_MResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MResponse.class, Builder.class);
      }

      // Construct using RpcResponse.MResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        url_ = "";

        message_ = "";

        resultType_ = 0;

        jsonResult_ = "";

        internalGetMutableResult().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcResponse.internal_static_MResponse_descriptor;
      }

      @Override
      public MResponse getDefaultInstanceForType() {
        return MResponse.getDefaultInstance();
      }

      @Override
      public MResponse build() {
        MResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MResponse buildPartial() {
        MResponse result = new MResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.code_ = code_;
        result.url_ = url_;
        result.message_ = message_;
        result.resultType_ = resultType_;
        result.jsonResult_ = jsonResult_;
        result.result_ = internalGetResult();
        result.result_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MResponse) {
          return mergeFrom((MResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MResponse other) {
        if (other == MResponse.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.resultType_ != 0) {
          setResultTypeValue(other.getResultTypeValue());
        }
        if (!other.getJsonResult().isEmpty()) {
          jsonResult_ = other.jsonResult_;
          onChanged();
        }
        internalGetMutableResult().mergeFrom(
            other.internalGetResult());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ = 0;
      /**
       * <pre>
       *返回类型
       * </pre>
       *
       * <code>.MResponse.Code code = 1;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <pre>
       *返回类型
       * </pre>
       *
       * <code>.MResponse.Code code = 1;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回类型
       * </pre>
       *
       * <code>.MResponse.Code code = 1;</code>
       */
      public Code getCode() {
        @SuppressWarnings("deprecation")
        Code result = Code.valueOf(code_);
        return result == null ? Code.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *返回类型
       * </pre>
       *
       * <code>.MResponse.Code code = 1;</code>
       */
      public Builder setCode(Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回类型
       * </pre>
       *
       * <code>.MResponse.Code code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <pre>
       *返回路由
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *返回路由
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *返回路由
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回路由
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回路由
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       *消息提示
       * </pre>
       *
       * <code>string message = 3;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息提示
       * </pre>
       *
       * <code>string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息提示
       * </pre>
       *
       * <code>string message = 3;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息提示
       * </pre>
       *
       * <code>string message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息提示
       * </pre>
       *
       * <code>string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private int resultType_ = 0;
      /**
       * <pre>
       *返回的数据类型
       * </pre>
       *
       * <code>.MResponse.ResultType resultType = 4;</code>
       */
      public int getResultTypeValue() {
        return resultType_;
      }
      /**
       * <pre>
       *返回的数据类型
       * </pre>
       *
       * <code>.MResponse.ResultType resultType = 4;</code>
       */
      public Builder setResultTypeValue(int value) {
        resultType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回的数据类型
       * </pre>
       *
       * <code>.MResponse.ResultType resultType = 4;</code>
       */
      public ResultType getResultType() {
        @SuppressWarnings("deprecation")
        ResultType result = ResultType.valueOf(resultType_);
        return result == null ? ResultType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *返回的数据类型
       * </pre>
       *
       * <code>.MResponse.ResultType resultType = 4;</code>
       */
      public Builder setResultType(ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resultType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回的数据类型
       * </pre>
       *
       * <code>.MResponse.ResultType resultType = 4;</code>
       */
      public Builder clearResultType() {
        
        resultType_ = 0;
        onChanged();
        return this;
      }

      private Object jsonResult_ = "";
      /**
       * <pre>
       *json返回格式
       * </pre>
       *
       * <code>string jsonResult = 5;</code>
       */
      public String getJsonResult() {
        Object ref = jsonResult_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jsonResult_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *json返回格式
       * </pre>
       *
       * <code>string jsonResult = 5;</code>
       */
      public com.google.protobuf.ByteString
          getJsonResultBytes() {
        Object ref = jsonResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jsonResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *json返回格式
       * </pre>
       *
       * <code>string jsonResult = 5;</code>
       */
      public Builder setJsonResult(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *json返回格式
       * </pre>
       *
       * <code>string jsonResult = 5;</code>
       */
      public Builder clearJsonResult() {
        
        jsonResult_ = getDefaultInstance().getJsonResult();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *json返回格式
       * </pre>
       *
       * <code>string jsonResult = 5;</code>
       */
      public Builder setJsonResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonResult_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, com.google.protobuf.Any> result_;
      private com.google.protobuf.MapField<String, com.google.protobuf.Any>
      internalGetResult() {
        if (result_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResultDefaultEntryHolder.defaultEntry);
        }
        return result_;
      }
      private com.google.protobuf.MapField<String, com.google.protobuf.Any>
      internalGetMutableResult() {
        onChanged();;
        if (result_ == null) {
          result_ = com.google.protobuf.MapField.newMapField(
              ResultDefaultEntryHolder.defaultEntry);
        }
        if (!result_.isMutable()) {
          result_ = result_.copy();
        }
        return result_;
      }

      public int getResultCount() {
        return internalGetResult().getMap().size();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */

      public boolean containsResult(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetResult().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResultMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Any> getResult() {
        return getResultMap();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */

      public java.util.Map<String, com.google.protobuf.Any> getResultMap() {
        return internalGetResult().getMap();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */

      public com.google.protobuf.Any getResultOrDefault(
          String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, com.google.protobuf.Any> map =
            internalGetResult().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */

      public com.google.protobuf.Any getResultOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, com.google.protobuf.Any> map =
            internalGetResult().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearResult() {
        internalGetMutableResult().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */

      public Builder removeResult(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableResult().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Any>
      getMutableResult() {
        return internalGetMutableResult().getMutableMap();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */
      public Builder putResult(
          String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableResult().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; result = 6;</code>
       */

      public Builder putAllResult(
          java.util.Map<String, com.google.protobuf.Any> values) {
        internalGetMutableResult().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MResponse)
    }

    // @@protoc_insertion_point(class_scope:MResponse)
    private static final MResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MResponse();
    }

    public static MResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MResponse>
        PARSER = new com.google.protobuf.AbstractParser<MResponse>() {
      @Override
      public MResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public MResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MResponse_ResultEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MResponse_ResultEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021RpcResponse.proto\032\031google/protobuf/any" +
      ".proto\"\311\002\n\tMResponse\022\035\n\004code\030\001 \001(\0162\017.MRe" +
      "sponse.Code\022\013\n\003url\030\002 \001(\t\022\017\n\007message\030\003 \001(" +
      "\t\022)\n\nresultType\030\004 \001(\0162\025.MResponse.Result" +
      "Type\022\022\n\njsonResult\030\005 \001(\t\022&\n\006result\030\006 \003(\013" +
      "2\026.MResponse.ResultEntry\032C\n\013ResultEntry\022" +
      "\013\n\003key\030\001 \001(\t\022#\n\005value\030\002 \001(\0132\024.google.pro" +
      "tobuf.Any:\0028\001\"/\n\004Code\022\013\n\007SUCCESS\020\000\022\013\n\007EX" +
      "_BUSS\020\001\022\r\n\tEX_SERVER\020\002\"\"\n\nResultType\022\010\n\004" +
      "JSON\020\000\022\n\n\006BINARY\020\001B\rB\013RpcResponseb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_MResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MResponse_descriptor,
        new String[] { "Code", "Url", "Message", "ResultType", "JsonResult", "Result", });
    internal_static_MResponse_ResultEntry_descriptor =
      internal_static_MResponse_descriptor.getNestedTypes().get(0);
    internal_static_MResponse_ResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MResponse_ResultEntry_descriptor,
        new String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
