package com.ga.wyc.domain.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRequest.proto

public final class RpcRequest {
  private RpcRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MRequest.MessageType messageType = 1;</code>
     */
    int getMessageTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MRequest.MessageType messageType = 1;</code>
     */
    MRequest.MessageType getMessageType();

    /**
     * <pre>
     *classname
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    String getUrl();
    /**
     * <pre>
     *classname
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     *jsonStr
     * </pre>
     *
     * <code>string jsonStr = 3;</code>
     */
    String getJsonStr();
    /**
     * <pre>
     *jsonStr
     * </pre>
     *
     * <code>string jsonStr = 3;</code>
     */
    com.google.protobuf.ByteString
        getJsonStrBytes();

    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */
    int getParamsCount();
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */
    boolean containsParams(
            String key);
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, com.google.protobuf.Any>
    getParams();
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */
    java.util.Map<String, com.google.protobuf.Any>
    getParamsMap();
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */

    com.google.protobuf.Any getParamsOrDefault(
            String key,
            com.google.protobuf.Any defaultValue);
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */

    com.google.protobuf.Any getParamsOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code MRequest}
   */
  public  static final class MRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MRequest)
      MRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MRequest.newBuilder() to construct.
    private MRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MRequest() {
      messageType_ = 0;
      url_ = "";
      jsonStr_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              jsonStr_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                params_ = com.google.protobuf.MapField.newMapField(
                    ParamsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<String, com.google.protobuf.Any>
              params__ = input.readMessage(
                  ParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              params_.getMutableMap().put(
                  params__.getKey(), params__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcRequest.internal_static_MRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcRequest.internal_static_MRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MRequest.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MRequest.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *JSON
       * </pre>
       *
       * <code>JSON = 0;</code>
       */
      JSON(0),
      /**
       * <pre>
       *BINARY
       * </pre>
       *
       * <code>BINARY = 1;</code>
       */
      BINARY(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *JSON
       * </pre>
       *
       * <code>JSON = 0;</code>
       */
      public static final int JSON_VALUE = 0;
      /**
       * <pre>
       *BINARY
       * </pre>
       *
       * <code>BINARY = 1;</code>
       */
      public static final int BINARY_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return JSON;
          case 1: return BINARY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MRequest.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MRequest.MessageType messageType = 1;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MRequest.MessageType messageType = 1;</code>
     */
    public MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile Object url_;
    /**
     * <pre>
     *classname
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *classname
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JSONSTR_FIELD_NUMBER = 3;
    private volatile Object jsonStr_;
    /**
     * <pre>
     *jsonStr
     * </pre>
     *
     * <code>string jsonStr = 3;</code>
     */
    public String getJsonStr() {
      Object ref = jsonStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jsonStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *jsonStr
     * </pre>
     *
     * <code>string jsonStr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getJsonStrBytes() {
      Object ref = jsonStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jsonStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private static final class ParamsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, com.google.protobuf.Any>newDefaultInstance(
                  RpcRequest.internal_static_MRequest_ParamsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, com.google.protobuf.Any> params_;
    private com.google.protobuf.MapField<String, com.google.protobuf.Any>
    internalGetParams() {
      if (params_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      return params_;
    }

    public int getParamsCount() {
      return internalGetParams().getMap().size();
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */

    public boolean containsParams(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, com.google.protobuf.Any> getParams() {
      return getParamsMap();
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */

    public java.util.Map<String, com.google.protobuf.Any> getParamsMap() {
      return internalGetParams().getMap();
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */

    public com.google.protobuf.Any getParamsOrDefault(
        String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, com.google.protobuf.Any> map =
          internalGetParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *序列化对象 N个
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
     */

    public com.google.protobuf.Any getParamsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, com.google.protobuf.Any> map =
          internalGetParams().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != MessageType.JSON.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
      if (!getJsonStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonStr_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParams(),
          ParamsDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != MessageType.JSON.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      if (!getJsonStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonStr_);
      }
      for (java.util.Map.Entry<String, com.google.protobuf.Any> entry
           : internalGetParams().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, com.google.protobuf.Any>
        params__ = ParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, params__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MRequest)) {
        return super.equals(obj);
      }
      MRequest other = (MRequest) obj;

      boolean result = true;
      result = result && messageType_ == other.messageType_;
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && getJsonStr()
          .equals(other.getJsonStr());
      result = result && internalGetParams().equals(
          other.internalGetParams());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + JSONSTR_FIELD_NUMBER;
      hash = (53 * hash) + getJsonStr().hashCode();
      if (!internalGetParams().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MRequest)
        MRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcRequest.internal_static_MRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcRequest.internal_static_MRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MRequest.class, Builder.class);
      }

      // Construct using RpcRequest.MRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        url_ = "";

        jsonStr_ = "";

        internalGetMutableParams().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcRequest.internal_static_MRequest_descriptor;
      }

      @Override
      public MRequest getDefaultInstanceForType() {
        return MRequest.getDefaultInstance();
      }

      @Override
      public MRequest build() {
        MRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MRequest buildPartial() {
        MRequest result = new MRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.messageType_ = messageType_;
        result.url_ = url_;
        result.jsonStr_ = jsonStr_;
        result.params_ = internalGetParams();
        result.params_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MRequest) {
          return mergeFrom((MRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MRequest other) {
        if (other == MRequest.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getJsonStr().isEmpty()) {
          jsonStr_ = other.jsonStr_;
          onChanged();
        }
        internalGetMutableParams().mergeFrom(
            other.internalGetParams());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int messageType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MRequest.MessageType messageType = 1;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MRequest.MessageType messageType = 1;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MRequest.MessageType messageType = 1;</code>
       */
      public MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(messageType_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MRequest.MessageType messageType = 1;</code>
       */
      public Builder setMessageType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MRequest.MessageType messageType = 1;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <pre>
       *classname
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *classname
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *classname
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *classname
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *classname
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private Object jsonStr_ = "";
      /**
       * <pre>
       *jsonStr
       * </pre>
       *
       * <code>string jsonStr = 3;</code>
       */
      public String getJsonStr() {
        Object ref = jsonStr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jsonStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *jsonStr
       * </pre>
       *
       * <code>string jsonStr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getJsonStrBytes() {
        Object ref = jsonStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jsonStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *jsonStr
       * </pre>
       *
       * <code>string jsonStr = 3;</code>
       */
      public Builder setJsonStr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *jsonStr
       * </pre>
       *
       * <code>string jsonStr = 3;</code>
       */
      public Builder clearJsonStr() {
        
        jsonStr_ = getDefaultInstance().getJsonStr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *jsonStr
       * </pre>
       *
       * <code>string jsonStr = 3;</code>
       */
      public Builder setJsonStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonStr_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, com.google.protobuf.Any> params_;
      private com.google.protobuf.MapField<String, com.google.protobuf.Any>
      internalGetParams() {
        if (params_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParamsDefaultEntryHolder.defaultEntry);
        }
        return params_;
      }
      private com.google.protobuf.MapField<String, com.google.protobuf.Any>
      internalGetMutableParams() {
        onChanged();;
        if (params_ == null) {
          params_ = com.google.protobuf.MapField.newMapField(
              ParamsDefaultEntryHolder.defaultEntry);
        }
        if (!params_.isMutable()) {
          params_ = params_.copy();
        }
        return params_;
      }

      public int getParamsCount() {
        return internalGetParams().getMap().size();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */

      public boolean containsParams(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetParams().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParamsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Any> getParams() {
        return getParamsMap();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */

      public java.util.Map<String, com.google.protobuf.Any> getParamsMap() {
        return internalGetParams().getMap();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */

      public com.google.protobuf.Any getParamsOrDefault(
          String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, com.google.protobuf.Any> map =
            internalGetParams().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */

      public com.google.protobuf.Any getParamsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, com.google.protobuf.Any> map =
            internalGetParams().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParams() {
        internalGetMutableParams().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */

      public Builder removeParams(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableParams().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Any>
      getMutableParams() {
        return internalGetMutableParams().getMutableMap();
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */
      public Builder putParams(
          String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableParams().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *序列化对象 N个
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; params = 4;</code>
       */

      public Builder putAllParams(
          java.util.Map<String, com.google.protobuf.Any> values) {
        internalGetMutableParams().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MRequest)
    }

    // @@protoc_insertion_point(class_scope:MRequest)
    private static final MRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MRequest();
    }

    public static MRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MRequest>
        PARSER = new com.google.protobuf.AbstractParser<MRequest>() {
      @Override
      public MRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public MRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MRequest_ParamsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MRequest_ParamsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RpcRequest.proto\032\031google/protobuf/any." +
      "proto\"\345\001\n\010MRequest\022*\n\013messageType\030\001 \001(\0162" +
      "\025.MRequest.MessageType\022\013\n\003url\030\002 \001(\t\022\017\n\007j" +
      "sonStr\030\003 \001(\t\022%\n\006params\030\004 \003(\0132\025.MRequest." +
      "ParamsEntry\032C\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022" +
      "#\n\005value\030\002 \001(\0132\024.google.protobuf.Any:\0028\001" +
      "\"#\n\013MessageType\022\010\n\004JSON\020\000\022\n\n\006BINARY\020\001B\014B" +
      "\nRpcRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_MRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MRequest_descriptor,
        new String[] { "MessageType", "Url", "JsonStr", "Params", });
    internal_static_MRequest_ParamsEntry_descriptor =
      internal_static_MRequest_descriptor.getNestedTypes().get(0);
    internal_static_MRequest_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MRequest_ParamsEntry_descriptor,
        new String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
